// Code generated by "httpsnoop/codegen"; DO NOT EDIT.

package httpsnoop

import (
	"bufio"
	"io"
	"net"
	"net/http"
	"time"
)

// HeaderFunc is part of the http.ResponseWriter interface.
type HeaderFunc func() http.Header

// WriteHeaderFunc is part of the http.ResponseWriter interface.
type WriteHeaderFunc func(code int)

// WriteFunc is part of the http.ResponseWriter interface.
type WriteFunc func(b []byte) (int, error)

// FlushFunc is part of the http.Flusher interface.
type FlushFunc func()

// CloseNotifyFunc is part of the http.CloseNotifier interface.
type CloseNotifyFunc func() <-chan bool

// HijackFunc is part of the http.Hijacker interface.
type HijackFunc func() (net.Conn, *bufio.ReadWriter, error)

// ReadFromFunc is part of the io.ReaderFrom interface.
type ReadFromFunc func(src io.Reader) (int64, error)

// SetReadDeadlineFunc is part of the deadliner interface.
type SetReadDeadlineFunc func(deadline time.Time) error

// SetWriteDeadlineFunc is part of the deadliner interface.
type SetWriteDeadlineFunc func(deadline time.Time) error

// EnableFullDuplexFunc is part of the fullDuplexEnabler interface.
type EnableFullDuplexFunc func() error

// PushFunc is part of the http.Pusher interface.
type PushFunc func(target string, opts *http.PushOptions) error

// WriteStringFunc is part of the io.StringWriter interface.
type WriteStringFunc func(s string) (int, error)

// Hooks defines a set of method interceptors for methods included in
// http.ResponseWriter as well as some others. You can think of them as
// middleware for the function calls they target. See Wrap for more details.
type Hooks struct {
	Header           func(HeaderFunc) HeaderFunc
	WriteHeader      func(WriteHeaderFunc) WriteHeaderFunc
	Write            func(WriteFunc) WriteFunc
	Flush            func(FlushFunc) FlushFunc
	CloseNotify      func(CloseNotifyFunc) CloseNotifyFunc
	Hijack           func(HijackFunc) HijackFunc
	ReadFrom         func(ReadFromFunc) ReadFromFunc
	SetReadDeadline  func(SetReadDeadlineFunc) SetReadDeadlineFunc
	SetWriteDeadline func(SetWriteDeadlineFunc) SetWriteDeadlineFunc
	EnableFullDuplex func(EnableFullDuplexFunc) EnableFullDuplexFunc
	Push             func(PushFunc) PushFunc
	WriteString      func(WriteStringFunc) WriteStringFunc
}

// Wrap returns a wrapped version of w that provides the exact same interface
// as w. Specifically if w implements any combination of:
//
// - http.Flusher
// - http.CloseNotifier
// - http.Hijacker
// - io.ReaderFrom
// - deadliner
// - fullDuplexEnabler
// - http.Pusher
// - io.StringWriter
//
// The wrapped version will implement the exact same combination. If no hooks
// are set, the wrapped version also behaves exactly as w. Hooks targeting
// methods not supported by w are ignored. Any other hooks will intercept the
// method they target and may modify the call's arguments and/or return values.
// The CaptureMetrics implementation serves as a working example for how the
// hooks can be used.
func Wrap(w http.ResponseWriter, hooks Hooks) http.ResponseWriter {
	rw := &rw{w: w}
	if hooks.Header != nil {
		rw.header = hooks.Header(w.Header)
	}
	if hooks.WriteHeader != nil {
		rw.writeHeader = hooks.WriteHeader(w.WriteHeader)
	}
	if hooks.Write != nil {
		rw.write = hooks.Write(w.Write)
	}
	t0, i0 := w.(http.Flusher)
	if i0 && hooks.Flush != nil {
		rw.flush = hooks.Flush(t0.Flush)
	}
	t1, i1 := w.(http.CloseNotifier)
	if i1 && hooks.CloseNotify != nil {
		rw.closeNotify = hooks.CloseNotify(t1.CloseNotify)
	}
	t2, i2 := w.(http.Hijacker)
	if i2 && hooks.Hijack != nil {
		rw.hijack = hooks.Hijack(t2.Hijack)
	}
	t3, i3 := w.(io.ReaderFrom)
	if i3 && hooks.ReadFrom != nil {
		rw.readFrom = hooks.ReadFrom(t3.ReadFrom)
	}
	t4, i4 := w.(deadliner)
	if i4 && hooks.SetReadDeadline != nil {
		rw.setReadDeadline = hooks.SetReadDeadline(t4.SetReadDeadline)
	}
	if i4 && hooks.SetWriteDeadline != nil {
		rw.setWriteDeadline = hooks.SetWriteDeadline(t4.SetWriteDeadline)
	}
	t5, i5 := w.(fullDuplexEnabler)
	if i5 && hooks.EnableFullDuplex != nil {
		rw.enableFullDuplex = hooks.EnableFullDuplex(t5.EnableFullDuplex)
	}
	t6, i6 := w.(http.Pusher)
	if i6 && hooks.Push != nil {
		rw.push = hooks.Push(t6.Push)
	}
	t7, i7 := w.(io.StringWriter)
	if i7 && hooks.WriteString != nil {
		rw.writeString = hooks.WriteString(t7.WriteString)
	}
	switch {
	// combination 1/256
	case !i0 && !i1 && !i2 && !i3 && !i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
		}{rw, rw}
	// combination 2/256
	case !i0 && !i1 && !i2 && !i3 && !i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			io.StringWriter
		}{rw, rw, rw}
	// combination 3/256
	case !i0 && !i1 && !i2 && !i3 && !i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Pusher
		}{rw, rw, rw}
	// combination 4/256
	case !i0 && !i1 && !i2 && !i3 && !i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw}
	// combination 5/256
	case !i0 && !i1 && !i2 && !i3 && !i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			fullDuplexEnabler
		}{rw, rw, rw}
	// combination 6/256
	case !i0 && !i1 && !i2 && !i3 && !i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw}
	// combination 7/256
	case !i0 && !i1 && !i2 && !i3 && !i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw}
	// combination 8/256
	case !i0 && !i1 && !i2 && !i3 && !i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 9/256
	case !i0 && !i1 && !i2 && !i3 && i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			deadliner
		}{rw, rw, rw}
	// combination 10/256
	case !i0 && !i1 && !i2 && !i3 && i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			deadliner
			io.StringWriter
		}{rw, rw, rw, rw}
	// combination 11/256
	case !i0 && !i1 && !i2 && !i3 && i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			deadliner
			http.Pusher
		}{rw, rw, rw, rw}
	// combination 12/256
	case !i0 && !i1 && !i2 && !i3 && i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			deadliner
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 13/256
	case !i0 && !i1 && !i2 && !i3 && i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			deadliner
			fullDuplexEnabler
		}{rw, rw, rw, rw}
	// combination 14/256
	case !i0 && !i1 && !i2 && !i3 && i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			deadliner
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 15/256
	case !i0 && !i1 && !i2 && !i3 && i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			deadliner
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw}
	// combination 16/256
	case !i0 && !i1 && !i2 && !i3 && i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			deadliner
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 17/256
	case !i0 && !i1 && !i2 && i3 && !i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			io.ReaderFrom
		}{rw, rw, rw}
	// combination 18/256
	case !i0 && !i1 && !i2 && i3 && !i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			io.ReaderFrom
			io.StringWriter
		}{rw, rw, rw, rw}
	// combination 19/256
	case !i0 && !i1 && !i2 && i3 && !i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			io.ReaderFrom
			http.Pusher
		}{rw, rw, rw, rw}
	// combination 20/256
	case !i0 && !i1 && !i2 && i3 && !i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			io.ReaderFrom
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 21/256
	case !i0 && !i1 && !i2 && i3 && !i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			io.ReaderFrom
			fullDuplexEnabler
		}{rw, rw, rw, rw}
	// combination 22/256
	case !i0 && !i1 && !i2 && i3 && !i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			io.ReaderFrom
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 23/256
	case !i0 && !i1 && !i2 && i3 && !i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			io.ReaderFrom
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw}
	// combination 24/256
	case !i0 && !i1 && !i2 && i3 && !i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			io.ReaderFrom
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 25/256
	case !i0 && !i1 && !i2 && i3 && i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			io.ReaderFrom
			deadliner
		}{rw, rw, rw, rw}
	// combination 26/256
	case !i0 && !i1 && !i2 && i3 && i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			io.ReaderFrom
			deadliner
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 27/256
	case !i0 && !i1 && !i2 && i3 && i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			io.ReaderFrom
			deadliner
			http.Pusher
		}{rw, rw, rw, rw, rw}
	// combination 28/256
	case !i0 && !i1 && !i2 && i3 && i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			io.ReaderFrom
			deadliner
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 29/256
	case !i0 && !i1 && !i2 && i3 && i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw}
	// combination 30/256
	case !i0 && !i1 && !i2 && i3 && i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 31/256
	case !i0 && !i1 && !i2 && i3 && i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 32/256
	case !i0 && !i1 && !i2 && i3 && i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 33/256
	case !i0 && !i1 && i2 && !i3 && !i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
		}{rw, rw, rw}
	// combination 34/256
	case !i0 && !i1 && i2 && !i3 && !i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			io.StringWriter
		}{rw, rw, rw, rw}
	// combination 35/256
	case !i0 && !i1 && i2 && !i3 && !i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			http.Pusher
		}{rw, rw, rw, rw}
	// combination 36/256
	case !i0 && !i1 && i2 && !i3 && !i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 37/256
	case !i0 && !i1 && i2 && !i3 && !i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			fullDuplexEnabler
		}{rw, rw, rw, rw}
	// combination 38/256
	case !i0 && !i1 && i2 && !i3 && !i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 39/256
	case !i0 && !i1 && i2 && !i3 && !i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw}
	// combination 40/256
	case !i0 && !i1 && i2 && !i3 && !i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 41/256
	case !i0 && !i1 && i2 && !i3 && i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			deadliner
		}{rw, rw, rw, rw}
	// combination 42/256
	case !i0 && !i1 && i2 && !i3 && i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			deadliner
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 43/256
	case !i0 && !i1 && i2 && !i3 && i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			deadliner
			http.Pusher
		}{rw, rw, rw, rw, rw}
	// combination 44/256
	case !i0 && !i1 && i2 && !i3 && i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			deadliner
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 45/256
	case !i0 && !i1 && i2 && !i3 && i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			deadliner
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw}
	// combination 46/256
	case !i0 && !i1 && i2 && !i3 && i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			deadliner
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 47/256
	case !i0 && !i1 && i2 && !i3 && i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			deadliner
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 48/256
	case !i0 && !i1 && i2 && !i3 && i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			deadliner
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 49/256
	case !i0 && !i1 && i2 && i3 && !i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			io.ReaderFrom
		}{rw, rw, rw, rw}
	// combination 50/256
	case !i0 && !i1 && i2 && i3 && !i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			io.ReaderFrom
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 51/256
	case !i0 && !i1 && i2 && i3 && !i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			io.ReaderFrom
			http.Pusher
		}{rw, rw, rw, rw, rw}
	// combination 52/256
	case !i0 && !i1 && i2 && i3 && !i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			io.ReaderFrom
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 53/256
	case !i0 && !i1 && i2 && i3 && !i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			io.ReaderFrom
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw}
	// combination 54/256
	case !i0 && !i1 && i2 && i3 && !i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			io.ReaderFrom
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 55/256
	case !i0 && !i1 && i2 && i3 && !i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			io.ReaderFrom
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 56/256
	case !i0 && !i1 && i2 && i3 && !i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			io.ReaderFrom
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 57/256
	case !i0 && !i1 && i2 && i3 && i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			io.ReaderFrom
			deadliner
		}{rw, rw, rw, rw, rw}
	// combination 58/256
	case !i0 && !i1 && i2 && i3 && i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			io.ReaderFrom
			deadliner
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 59/256
	case !i0 && !i1 && i2 && i3 && i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			io.ReaderFrom
			deadliner
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 60/256
	case !i0 && !i1 && i2 && i3 && i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			io.ReaderFrom
			deadliner
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 61/256
	case !i0 && !i1 && i2 && i3 && i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw, rw}
	// combination 62/256
	case !i0 && !i1 && i2 && i3 && i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 63/256
	case !i0 && !i1 && i2 && i3 && i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 64/256
	case !i0 && !i1 && i2 && i3 && i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Hijacker
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 65/256
	case !i0 && i1 && !i2 && !i3 && !i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
		}{rw, rw, rw}
	// combination 66/256
	case !i0 && i1 && !i2 && !i3 && !i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			io.StringWriter
		}{rw, rw, rw, rw}
	// combination 67/256
	case !i0 && i1 && !i2 && !i3 && !i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Pusher
		}{rw, rw, rw, rw}
	// combination 68/256
	case !i0 && i1 && !i2 && !i3 && !i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 69/256
	case !i0 && i1 && !i2 && !i3 && !i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			fullDuplexEnabler
		}{rw, rw, rw, rw}
	// combination 70/256
	case !i0 && i1 && !i2 && !i3 && !i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 71/256
	case !i0 && i1 && !i2 && !i3 && !i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw}
	// combination 72/256
	case !i0 && i1 && !i2 && !i3 && !i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 73/256
	case !i0 && i1 && !i2 && !i3 && i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			deadliner
		}{rw, rw, rw, rw}
	// combination 74/256
	case !i0 && i1 && !i2 && !i3 && i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			deadliner
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 75/256
	case !i0 && i1 && !i2 && !i3 && i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			deadliner
			http.Pusher
		}{rw, rw, rw, rw, rw}
	// combination 76/256
	case !i0 && i1 && !i2 && !i3 && i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			deadliner
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 77/256
	case !i0 && i1 && !i2 && !i3 && i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			deadliner
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw}
	// combination 78/256
	case !i0 && i1 && !i2 && !i3 && i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			deadliner
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 79/256
	case !i0 && i1 && !i2 && !i3 && i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			deadliner
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 80/256
	case !i0 && i1 && !i2 && !i3 && i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			deadliner
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 81/256
	case !i0 && i1 && !i2 && i3 && !i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			io.ReaderFrom
		}{rw, rw, rw, rw}
	// combination 82/256
	case !i0 && i1 && !i2 && i3 && !i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			io.ReaderFrom
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 83/256
	case !i0 && i1 && !i2 && i3 && !i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			io.ReaderFrom
			http.Pusher
		}{rw, rw, rw, rw, rw}
	// combination 84/256
	case !i0 && i1 && !i2 && i3 && !i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			io.ReaderFrom
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 85/256
	case !i0 && i1 && !i2 && i3 && !i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			io.ReaderFrom
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw}
	// combination 86/256
	case !i0 && i1 && !i2 && i3 && !i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			io.ReaderFrom
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 87/256
	case !i0 && i1 && !i2 && i3 && !i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			io.ReaderFrom
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 88/256
	case !i0 && i1 && !i2 && i3 && !i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			io.ReaderFrom
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 89/256
	case !i0 && i1 && !i2 && i3 && i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			io.ReaderFrom
			deadliner
		}{rw, rw, rw, rw, rw}
	// combination 90/256
	case !i0 && i1 && !i2 && i3 && i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			io.ReaderFrom
			deadliner
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 91/256
	case !i0 && i1 && !i2 && i3 && i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			io.ReaderFrom
			deadliner
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 92/256
	case !i0 && i1 && !i2 && i3 && i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			io.ReaderFrom
			deadliner
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 93/256
	case !i0 && i1 && !i2 && i3 && i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw, rw}
	// combination 94/256
	case !i0 && i1 && !i2 && i3 && i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 95/256
	case !i0 && i1 && !i2 && i3 && i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 96/256
	case !i0 && i1 && !i2 && i3 && i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 97/256
	case !i0 && i1 && i2 && !i3 && !i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
		}{rw, rw, rw, rw}
	// combination 98/256
	case !i0 && i1 && i2 && !i3 && !i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 99/256
	case !i0 && i1 && i2 && !i3 && !i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			http.Pusher
		}{rw, rw, rw, rw, rw}
	// combination 100/256
	case !i0 && i1 && i2 && !i3 && !i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 101/256
	case !i0 && i1 && i2 && !i3 && !i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw}
	// combination 102/256
	case !i0 && i1 && i2 && !i3 && !i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 103/256
	case !i0 && i1 && i2 && !i3 && !i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 104/256
	case !i0 && i1 && i2 && !i3 && !i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 105/256
	case !i0 && i1 && i2 && !i3 && i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			deadliner
		}{rw, rw, rw, rw, rw}
	// combination 106/256
	case !i0 && i1 && i2 && !i3 && i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			deadliner
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 107/256
	case !i0 && i1 && i2 && !i3 && i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			deadliner
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 108/256
	case !i0 && i1 && i2 && !i3 && i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			deadliner
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 109/256
	case !i0 && i1 && i2 && !i3 && i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			deadliner
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw, rw}
	// combination 110/256
	case !i0 && i1 && i2 && !i3 && i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			deadliner
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 111/256
	case !i0 && i1 && i2 && !i3 && i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			deadliner
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 112/256
	case !i0 && i1 && i2 && !i3 && i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			deadliner
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 113/256
	case !i0 && i1 && i2 && i3 && !i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
		}{rw, rw, rw, rw, rw}
	// combination 114/256
	case !i0 && i1 && i2 && i3 && !i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 115/256
	case !i0 && i1 && i2 && i3 && !i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 116/256
	case !i0 && i1 && i2 && i3 && !i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 117/256
	case !i0 && i1 && i2 && i3 && !i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw, rw}
	// combination 118/256
	case !i0 && i1 && i2 && i3 && !i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 119/256
	case !i0 && i1 && i2 && i3 && !i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 120/256
	case !i0 && i1 && i2 && i3 && !i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 121/256
	case !i0 && i1 && i2 && i3 && i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			deadliner
		}{rw, rw, rw, rw, rw, rw}
	// combination 122/256
	case !i0 && i1 && i2 && i3 && i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			deadliner
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 123/256
	case !i0 && i1 && i2 && i3 && i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			deadliner
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 124/256
	case !i0 && i1 && i2 && i3 && i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			deadliner
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 125/256
	case !i0 && i1 && i2 && i3 && i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 126/256
	case !i0 && i1 && i2 && i3 && i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 127/256
	case !i0 && i1 && i2 && i3 && i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 128/256
	case !i0 && i1 && i2 && i3 && i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 129/256
	case i0 && !i1 && !i2 && !i3 && !i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
		}{rw, rw, rw}
	// combination 130/256
	case i0 && !i1 && !i2 && !i3 && !i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			io.StringWriter
		}{rw, rw, rw, rw}
	// combination 131/256
	case i0 && !i1 && !i2 && !i3 && !i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Pusher
		}{rw, rw, rw, rw}
	// combination 132/256
	case i0 && !i1 && !i2 && !i3 && !i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 133/256
	case i0 && !i1 && !i2 && !i3 && !i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			fullDuplexEnabler
		}{rw, rw, rw, rw}
	// combination 134/256
	case i0 && !i1 && !i2 && !i3 && !i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 135/256
	case i0 && !i1 && !i2 && !i3 && !i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw}
	// combination 136/256
	case i0 && !i1 && !i2 && !i3 && !i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 137/256
	case i0 && !i1 && !i2 && !i3 && i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			deadliner
		}{rw, rw, rw, rw}
	// combination 138/256
	case i0 && !i1 && !i2 && !i3 && i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			deadliner
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 139/256
	case i0 && !i1 && !i2 && !i3 && i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			deadliner
			http.Pusher
		}{rw, rw, rw, rw, rw}
	// combination 140/256
	case i0 && !i1 && !i2 && !i3 && i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			deadliner
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 141/256
	case i0 && !i1 && !i2 && !i3 && i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			deadliner
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw}
	// combination 142/256
	case i0 && !i1 && !i2 && !i3 && i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			deadliner
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 143/256
	case i0 && !i1 && !i2 && !i3 && i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			deadliner
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 144/256
	case i0 && !i1 && !i2 && !i3 && i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			deadliner
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 145/256
	case i0 && !i1 && !i2 && i3 && !i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			io.ReaderFrom
		}{rw, rw, rw, rw}
	// combination 146/256
	case i0 && !i1 && !i2 && i3 && !i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			io.ReaderFrom
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 147/256
	case i0 && !i1 && !i2 && i3 && !i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			io.ReaderFrom
			http.Pusher
		}{rw, rw, rw, rw, rw}
	// combination 148/256
	case i0 && !i1 && !i2 && i3 && !i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			io.ReaderFrom
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 149/256
	case i0 && !i1 && !i2 && i3 && !i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			io.ReaderFrom
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw}
	// combination 150/256
	case i0 && !i1 && !i2 && i3 && !i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			io.ReaderFrom
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 151/256
	case i0 && !i1 && !i2 && i3 && !i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			io.ReaderFrom
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 152/256
	case i0 && !i1 && !i2 && i3 && !i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			io.ReaderFrom
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 153/256
	case i0 && !i1 && !i2 && i3 && i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			io.ReaderFrom
			deadliner
		}{rw, rw, rw, rw, rw}
	// combination 154/256
	case i0 && !i1 && !i2 && i3 && i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			io.ReaderFrom
			deadliner
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 155/256
	case i0 && !i1 && !i2 && i3 && i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			io.ReaderFrom
			deadliner
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 156/256
	case i0 && !i1 && !i2 && i3 && i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			io.ReaderFrom
			deadliner
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 157/256
	case i0 && !i1 && !i2 && i3 && i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw, rw}
	// combination 158/256
	case i0 && !i1 && !i2 && i3 && i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 159/256
	case i0 && !i1 && !i2 && i3 && i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 160/256
	case i0 && !i1 && !i2 && i3 && i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 161/256
	case i0 && !i1 && i2 && !i3 && !i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
		}{rw, rw, rw, rw}
	// combination 162/256
	case i0 && !i1 && i2 && !i3 && !i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 163/256
	case i0 && !i1 && i2 && !i3 && !i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			http.Pusher
		}{rw, rw, rw, rw, rw}
	// combination 164/256
	case i0 && !i1 && i2 && !i3 && !i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 165/256
	case i0 && !i1 && i2 && !i3 && !i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw}
	// combination 166/256
	case i0 && !i1 && i2 && !i3 && !i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 167/256
	case i0 && !i1 && i2 && !i3 && !i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 168/256
	case i0 && !i1 && i2 && !i3 && !i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 169/256
	case i0 && !i1 && i2 && !i3 && i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			deadliner
		}{rw, rw, rw, rw, rw}
	// combination 170/256
	case i0 && !i1 && i2 && !i3 && i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			deadliner
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 171/256
	case i0 && !i1 && i2 && !i3 && i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			deadliner
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 172/256
	case i0 && !i1 && i2 && !i3 && i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			deadliner
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 173/256
	case i0 && !i1 && i2 && !i3 && i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			deadliner
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw, rw}
	// combination 174/256
	case i0 && !i1 && i2 && !i3 && i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			deadliner
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 175/256
	case i0 && !i1 && i2 && !i3 && i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			deadliner
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 176/256
	case i0 && !i1 && i2 && !i3 && i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			deadliner
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 177/256
	case i0 && !i1 && i2 && i3 && !i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			io.ReaderFrom
		}{rw, rw, rw, rw, rw}
	// combination 178/256
	case i0 && !i1 && i2 && i3 && !i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			io.ReaderFrom
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 179/256
	case i0 && !i1 && i2 && i3 && !i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			io.ReaderFrom
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 180/256
	case i0 && !i1 && i2 && i3 && !i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			io.ReaderFrom
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 181/256
	case i0 && !i1 && i2 && i3 && !i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			io.ReaderFrom
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw, rw}
	// combination 182/256
	case i0 && !i1 && i2 && i3 && !i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			io.ReaderFrom
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 183/256
	case i0 && !i1 && i2 && i3 && !i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			io.ReaderFrom
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 184/256
	case i0 && !i1 && i2 && i3 && !i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			io.ReaderFrom
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 185/256
	case i0 && !i1 && i2 && i3 && i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			io.ReaderFrom
			deadliner
		}{rw, rw, rw, rw, rw, rw}
	// combination 186/256
	case i0 && !i1 && i2 && i3 && i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			io.ReaderFrom
			deadliner
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 187/256
	case i0 && !i1 && i2 && i3 && i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			io.ReaderFrom
			deadliner
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 188/256
	case i0 && !i1 && i2 && i3 && i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			io.ReaderFrom
			deadliner
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 189/256
	case i0 && !i1 && i2 && i3 && i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 190/256
	case i0 && !i1 && i2 && i3 && i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 191/256
	case i0 && !i1 && i2 && i3 && i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 192/256
	case i0 && !i1 && i2 && i3 && i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.Hijacker
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 193/256
	case i0 && i1 && !i2 && !i3 && !i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
		}{rw, rw, rw, rw}
	// combination 194/256
	case i0 && i1 && !i2 && !i3 && !i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			io.StringWriter
		}{rw, rw, rw, rw, rw}
	// combination 195/256
	case i0 && i1 && !i2 && !i3 && !i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Pusher
		}{rw, rw, rw, rw, rw}
	// combination 196/256
	case i0 && i1 && !i2 && !i3 && !i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 197/256
	case i0 && i1 && !i2 && !i3 && !i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw}
	// combination 198/256
	case i0 && i1 && !i2 && !i3 && !i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 199/256
	case i0 && i1 && !i2 && !i3 && !i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 200/256
	case i0 && i1 && !i2 && !i3 && !i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 201/256
	case i0 && i1 && !i2 && !i3 && i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			deadliner
		}{rw, rw, rw, rw, rw}
	// combination 202/256
	case i0 && i1 && !i2 && !i3 && i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			deadliner
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 203/256
	case i0 && i1 && !i2 && !i3 && i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			deadliner
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 204/256
	case i0 && i1 && !i2 && !i3 && i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			deadliner
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 205/256
	case i0 && i1 && !i2 && !i3 && i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			deadliner
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw, rw}
	// combination 206/256
	case i0 && i1 && !i2 && !i3 && i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			deadliner
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 207/256
	case i0 && i1 && !i2 && !i3 && i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			deadliner
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 208/256
	case i0 && i1 && !i2 && !i3 && i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			deadliner
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 209/256
	case i0 && i1 && !i2 && i3 && !i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			io.ReaderFrom
		}{rw, rw, rw, rw, rw}
	// combination 210/256
	case i0 && i1 && !i2 && i3 && !i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			io.ReaderFrom
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 211/256
	case i0 && i1 && !i2 && i3 && !i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			io.ReaderFrom
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 212/256
	case i0 && i1 && !i2 && i3 && !i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			io.ReaderFrom
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 213/256
	case i0 && i1 && !i2 && i3 && !i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			io.ReaderFrom
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw, rw}
	// combination 214/256
	case i0 && i1 && !i2 && i3 && !i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			io.ReaderFrom
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 215/256
	case i0 && i1 && !i2 && i3 && !i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			io.ReaderFrom
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 216/256
	case i0 && i1 && !i2 && i3 && !i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			io.ReaderFrom
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 217/256
	case i0 && i1 && !i2 && i3 && i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			io.ReaderFrom
			deadliner
		}{rw, rw, rw, rw, rw, rw}
	// combination 218/256
	case i0 && i1 && !i2 && i3 && i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			io.ReaderFrom
			deadliner
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 219/256
	case i0 && i1 && !i2 && i3 && i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			io.ReaderFrom
			deadliner
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 220/256
	case i0 && i1 && !i2 && i3 && i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			io.ReaderFrom
			deadliner
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 221/256
	case i0 && i1 && !i2 && i3 && i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 222/256
	case i0 && i1 && !i2 && i3 && i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 223/256
	case i0 && i1 && !i2 && i3 && i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 224/256
	case i0 && i1 && !i2 && i3 && i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 225/256
	case i0 && i1 && i2 && !i3 && !i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
		}{rw, rw, rw, rw, rw}
	// combination 226/256
	case i0 && i1 && i2 && !i3 && !i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw}
	// combination 227/256
	case i0 && i1 && i2 && !i3 && !i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			http.Pusher
		}{rw, rw, rw, rw, rw, rw}
	// combination 228/256
	case i0 && i1 && i2 && !i3 && !i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 229/256
	case i0 && i1 && i2 && !i3 && !i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw, rw}
	// combination 230/256
	case i0 && i1 && i2 && !i3 && !i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 231/256
	case i0 && i1 && i2 && !i3 && !i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 232/256
	case i0 && i1 && i2 && !i3 && !i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 233/256
	case i0 && i1 && i2 && !i3 && i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			deadliner
		}{rw, rw, rw, rw, rw, rw}
	// combination 234/256
	case i0 && i1 && i2 && !i3 && i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			deadliner
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 235/256
	case i0 && i1 && i2 && !i3 && i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			deadliner
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 236/256
	case i0 && i1 && i2 && !i3 && i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			deadliner
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 237/256
	case i0 && i1 && i2 && !i3 && i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			deadliner
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 238/256
	case i0 && i1 && i2 && !i3 && i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			deadliner
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 239/256
	case i0 && i1 && i2 && !i3 && i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			deadliner
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 240/256
	case i0 && i1 && i2 && !i3 && i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			deadliner
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 241/256
	case i0 && i1 && i2 && i3 && !i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
		}{rw, rw, rw, rw, rw, rw}
	// combination 242/256
	case i0 && i1 && i2 && i3 && !i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 243/256
	case i0 && i1 && i2 && i3 && !i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 244/256
	case i0 && i1 && i2 && i3 && !i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 245/256
	case i0 && i1 && i2 && i3 && !i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 246/256
	case i0 && i1 && i2 && i3 && !i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 247/256
	case i0 && i1 && i2 && i3 && !i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 248/256
	case i0 && i1 && i2 && i3 && !i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 249/256
	case i0 && i1 && i2 && i3 && i4 && !i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			deadliner
		}{rw, rw, rw, rw, rw, rw, rw}
	// combination 250/256
	case i0 && i1 && i2 && i3 && i4 && !i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			deadliner
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 251/256
	case i0 && i1 && i2 && i3 && i4 && !i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			deadliner
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 252/256
	case i0 && i1 && i2 && i3 && i4 && !i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			deadliner
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 253/256
	case i0 && i1 && i2 && i3 && i4 && i5 && !i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
		}{rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 254/256
	case i0 && i1 && i2 && i3 && i4 && i5 && !i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 255/256
	case i0 && i1 && i2 && i3 && i4 && i5 && i6 && !i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			http.Pusher
		}{rw, rw, rw, rw, rw, rw, rw, rw, rw}
	// combination 256/256
	case i0 && i1 && i2 && i3 && i4 && i5 && i6 && i7:
		return struct {
			Unwrapper
			http.ResponseWriter
			http.Flusher
			http.CloseNotifier
			http.Hijacker
			io.ReaderFrom
			deadliner
			fullDuplexEnabler
			http.Pusher
			io.StringWriter
		}{rw, rw, rw, rw, rw, rw, rw, rw, rw, rw}
	}
	panic("unreachable")
}

type rw struct {
	w                http.ResponseWriter
	header           HeaderFunc
	writeHeader      WriteHeaderFunc
	write            WriteFunc
	flush            FlushFunc
	closeNotify      CloseNotifyFunc
	hijack           HijackFunc
	readFrom         ReadFromFunc
	setReadDeadline  SetReadDeadlineFunc
	setWriteDeadline SetWriteDeadlineFunc
	enableFullDuplex EnableFullDuplexFunc
	push             PushFunc
	writeString      WriteStringFunc
}

func (w *rw) Unwrap() http.ResponseWriter {
	return w.w
}

func (w *rw) Header() http.Header {
	if w.header != nil {
		return w.header()
	}
	return w.w.Header()
}

func (w *rw) WriteHeader(code int) {
	if w.writeHeader != nil {
		w.writeHeader(code)
		return
	}
	w.w.WriteHeader(code)
}

func (w *rw) Write(b []byte) (int, error) {
	if w.write != nil {
		return w.write(b)
	}
	return w.w.Write(b)
}

func (w *rw) Flush() {
	if w.flush != nil {
		w.flush()
		return
	}
	w.w.(http.Flusher).Flush()
}

func (w *rw) CloseNotify() <-chan bool {
	if w.closeNotify != nil {
		return w.closeNotify()
	}
	return w.w.(http.CloseNotifier).CloseNotify()
}

func (w *rw) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	if w.hijack != nil {
		return w.hijack()
	}
	return w.w.(http.Hijacker).Hijack()
}

func (w *rw) ReadFrom(src io.Reader) (int64, error) {
	if w.readFrom != nil {
		return w.readFrom(src)
	}
	return w.w.(io.ReaderFrom).ReadFrom(src)
}

func (w *rw) SetReadDeadline(deadline time.Time) error {
	if w.setReadDeadline != nil {
		return w.setReadDeadline(deadline)
	}
	return w.w.(deadliner).SetReadDeadline(deadline)
}

func (w *rw) SetWriteDeadline(deadline time.Time) error {
	if w.setWriteDeadline != nil {
		return w.setWriteDeadline(deadline)
	}
	return w.w.(deadliner).SetWriteDeadline(deadline)
}

func (w *rw) EnableFullDuplex() error {
	if w.enableFullDuplex != nil {
		return w.enableFullDuplex()
	}
	return w.w.(fullDuplexEnabler).EnableFullDuplex()
}

func (w *rw) Push(target string, opts *http.PushOptions) error {
	if w.push != nil {
		return w.push(target, opts)
	}
	return w.w.(http.Pusher).Push(target, opts)
}

func (w *rw) WriteString(s string) (int, error) {
	if w.writeString != nil {
		return w.writeString(s)
	}
	return w.w.(io.StringWriter).WriteString(s)
}

type Unwrapper interface {
	Unwrap() http.ResponseWriter
}

// Unwrap returns the underlying http.ResponseWriter from within zero or more
// layers of httpsnoop wrappers.
func Unwrap(w http.ResponseWriter) http.ResponseWriter {
	if rw, ok := w.(Unwrapper); ok {
		// recurse until rw.Unwrap() returns a non-Unwrapper
		return Unwrap(rw.Unwrap())
	} else {
		return w
	}
}
